INSERT INTO menu_items (item, description, price, type) VALUES
  ('Four Cheese Garlic Bread', 'Toasted French bread topped with Romano, cheddar, and parmesan with a light layer of roasted garlic butter', 650, 'appetizer'),
  ('Fried Calamari', 'Breaded calamari, lightly fried and served with a side of marinara sauce',  800, 'appetizer'),
  ('Sweet Onion Rings', 'Sweet Vidalias onions glazed with honey, deep fried in beet batter', 850, 'appetizer'),
  ('Roasted Red Pepper Hummus', 'Served with cucumber and grilled pita',  550, 'appetizer'),
  ('Potato Skins', 'Served with cheddar, sour cream and crispy bacon', 650, 'appetizer'),
  ('Smoked Chicken Quesadilla', 'Served with guacamole and salsa',  850, 'appetizer'),
  ('Grilled Chicken Sandwich', 'Marinated grilled chicken and mozzarella cheese, sprouts, and fresh spinach', 950, 'main'),
  ('Roasted Turkey Club', 'With bacon, smoked mozzarella, avocado, heirloom tomatoes and aioli on focaccia', 950, 'main'),
  ('Yellow Fin Tuna', 'Flash grilled in Asian spices and served on artisan sourdough', 1200, 'main'),
  ('Hickory Burger', 'Topped with cheddar cheese, hickory-smoked bacon and smoky barbecue sauce', 1100, 'main'),
  ('Sante Fe Burger', 'Pepper jack cheese, house-made guacamole, pico de Gallo and chipotle mayo', 1100, 'main'),
  ('Onion Burger', 'Caramelized onions with garlic mayo on an onion bun, topped with chopped green onions', 950, 'main'),
  ('Teriyaki Burger', 'Marinated in teriyaki sauce, and topped with grilled pineapple, green onions and garlic mayo', 1200, 'main'),
  ('Wild Swiss Mushroom Burger', 'Two layers of melted Swiss cheese, sautéed mushrooms and caramelized onions', 1200, 'main'),
  ('Greek Pizza', 'Salami red onions, and Kalamata olives topped with feta and mozzarella cheese', 1400, 'main'),
  ('Vegetarian Delight', 'Loaded with green peppers, mushrooms, tomato slices and black olives', 200, 'main'),
  ('Hawaiian Pizza', 'Ham, sweet onions and Hawaiian pineapple', 1200, 'main'),
  ('Lobster Tempura', 'Soft lobster served with sweet & sour sauce', 650, 'main'),
  ('Aged Crab', 'Sourced from the Gulf of Mexico, these crabs have been handpicked from the tender, yet firm arms of JayJay Ting. Served with a butter glaze, and a side of clam chowder',
  20000, 'main'),
  ('Soda', 'A selection of Coke, Pepsi, Sprite, Mountain Dew, and Crush', 200, 'drink'),
  ('Bottled Beer', 'A choice of either domestic or imported', 1200, 'drink'),
  ('Pitcher', 'A large pitcher of beer for you and your friends to enjoy', 2000, 'drink'),
  ('Neapolitan Cappuccino Cake', 'Cappuccino mousse, caramel-pretzel, and chocolate cake', 1200, 'dessert'),
  ('White Chocolate Cheesecake', 'Citrus shortbread cookie, seasonal berries and glazed with raspberry reduction', 900, 'dessert'),
  ('Maple Créme Brûlée ', 'Served with Cofee', 1050, 'dessert'),
  ('Molten Lava Cake', 'Warm chocolate cake with a gooey centre served with vanilla ice cream', 1050, 'dessert');
